development:
      adapter: postgresql
      encoding: unicode
      database: hellorails_dev
      pool: 5
      username: 
      password:

test:
      adapter: postgresql
      encoding: unicode
      database: hellorails_test
      pool: 5
      username: 
      password:

production:
      adapter: postgresql
      encoding: unicode
      database: hellorails_production
      pool: 5
      username: leungty
      password: st8ck1t!
      host: hellorails.cua2kztm1e7i.us-west-2.rds.amazonaws.com
      port: 5432